### ISSUE TITLE
Leave base64 out of the substring

### ISSUE THREAD

**Issue by lukeweng** [benjaminch/make-my-life-easier#1]
Should be `base64 = base64 + ("==")[0:(3*len(base64)%4)];`
https://github.com/BenjaminCh/make-my-life-easier/blob/569c3bcdc7fff3ae20621990c351ce955ca5b3cc/base-64-web-safe.go#L29

**Comment by benjaminch** [comment]
Done here 3cb95268a02eec030d4aa052a2e4093d345e9f19
(Changing a bit the methodology)
